-- MySQL Script generated by MySQL Workbench
-- Sun Sep  1 09:59:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbtest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `idunity` INT(11) NOT NULL AUTO_INCREMENT,
  `mUserUUID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idunity`),
  UNIQUE INDEX `idunity_UNIQUE` (`idunity` ASC),
  UNIQUE INDEX `mName_UNIQUE` (`mUserUUID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session` ;

CREATE TABLE IF NOT EXISTS `session` (
  `idsession` INT(11) NOT NULL AUTO_INCREMENT,
  `mSessionUUID` VARCHAR(45) NOT NULL,
  `users_idunity` INT(11) NOT NULL,
  `mTimeStamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idsession`, `users_idunity`),
  UNIQUE INDEX `idsession_UNIQUE` (`idsession` ASC),
  UNIQUE INDEX `mUUID_UNIQUE` (`mSessionUUID` ASC),
  INDEX `fk_session_users_idx` (`users_idunity` ASC),
  CONSTRAINT `fk_session_users`
    FOREIGN KEY (`users_idunity`)
    REFERENCES `users` (`idunity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event` ;

CREATE TABLE IF NOT EXISTS `event` (
  `idEvent` INT(11) NOT NULL AUTO_INCREMENT,
  `mName` VARCHAR(45) NULL DEFAULT NULL,
  `session_idsession` INT(11) NOT NULL,
  `session_users_idunity` INT(11) NOT NULL,
  PRIMARY KEY (`idEvent`, `session_idsession`, `session_users_idunity`),
  UNIQUE INDEX `idEvent_UNIQUE` (`idEvent` ASC),
  INDEX `fk_Event_session1_idx` (`session_idsession` ASC, `session_users_idunity` ASC),
  CONSTRAINT `fk_Event_session1`
    FOREIGN KEY (`session_idsession` , `session_users_idunity`)
    REFERENCES `session` (`idsession` , `users_idunity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
